#pragma once

#define VITA_TRACE_CORE_COUNT 4u
#define VITA_TRACE_DEFAULT_RING_BYTES (256u * 1024u)
#define VITA_TRACE_DEFAULT_SAMPLE_HZ 100u
#define VITA_TRACE_MODULE_NAME_MAX 28u
#define VITA_TRACE_MODULE_MAX_SEGMENTS 4u
